name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
      
    - name: Check version
      run: flutter --version
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Test project
      run: flutter test
      
    - name: Build APK
      run: flutter build apk --dart-define=BLOB_KEY=${{secrets.BLOB_KEY}}
      
    - name: Save APK
      uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
      
    
